character = ['Fighter', 'Cleric', 'Wizard', 'Warlock', 'Bard', 'Ranger', 'Barbarian', 'Rogue', 'Druid']
type = {'Chest':1, 'Legs':1, 'Foot':1, 'Hands':1, 'Primary Weapon':1, 'Necklace':1, 'Back':1, 'Head':1, 'Ring':2}
stat = {'Strength':'strength',
        'Vigor':'vigor',
        'Agility':'agility',
        'Dexterity':'dexterity',
        'Will':'will',
        'Knowledge':'knowledge',
        'Resourcfulness':'resourcfulness',
        'Max Health':'additional_max_health',
        'Max Health Bonus':'max_health_bonus',
        'Physical Power':'physical_power',
        'Magical Power':'magical_power',
        'Physical Damage Bonus':'physical_damage_bonus',
        'Magical Damage Bonus':'magical_damage_bonus',
        'Armor Rating':'armor',
        'Magic Resistance':'magic_resist',
        'Physical Damage Reduction':'physical_damage_reduction_bonus',
        'Magical Damage Reduction':'magical_damage_reduction_bonus',
        'Move Speed':'additional_move_speed',
        'Move Speed Bonus':'move_speed_bonus',
        'Action Speed':'additional_action_speed',
        'Spell Casting Speed':'additional_spell_casting_speed',
        'Buff Duration Bonus':'additional_buff_duration',
        'Debuff Duration Bonus':'additional_debuff_duration',
        'Regular Interaction Speed':'additional_regular_interaction_speed',
        'Magical Interaction Speed':'additional_magic_interaction_speed',
        'Magic Penetration':'magic_penetration',
        'Armor Penetration':'armor_penetration',
        'Projectile Damage Reduction':'projectile_damage_reduction',
        'Headshot Damage Reduction':'headshot_damage_reduction',
        'All Attributes':'all_attributes_bonus',
        'Magical Healing':'magical_healing',
        'True Physical Damage':'true_physical_damage',
        'True Magical Damage':'true_magical_damage',
        'Luck':'luck',
        'Additional Physical Damage':'additional_physical_damage',
        'Additional Magical Damage':'additional_magical_damage',
        'Weapon Damage':'weapon_damage'}
